### ISSUE TITLE
Player Not Centered

### ISSUE THREAD

**Issue by tremmelm123** [Lapask/fixed-resizable-hybrid#1]
Perhaps I have something configured incorrectly, but the player seems to be only centered whenever chat is hidden. I really like the set up for this plugin but it's a little hard to do certain things with the camera like this.

I don't know if this is of any help, but the plugin "Fixed Mode Hide Chat" recenters the player whenever it's toggled on or off.

**Comment by Lapask** [comment]
Good point. I usually play with the chat hidden but it might be a good idea to have a config option that makes the viewport change size if the chat is open. Only reason this might be a little tricky is because theres no simple way to recenter the camera without changing the size of the entire viewport (please correct me if i'm wrong), which in resized would leave black gaps where nothing is being rendered. 

The fixed-mode-hide-chat plugin shrinks the size of the viewport so nothing renders under the chat, but our plugin's chatbox isn't the entire width of the viewport (unless you're in the minimum dimensions, which is counterproductive). The result of this would be a black gap i'd have to figure out how to fill in. Maybe I could stretch the chatbox but i'd have to look into whether this is practical. 

Maybe its possible, but i'll work on getting some sort of solution working.

**Comment by Lapask** [comment]
@tremmelm123 what do you think about something like this? 
It would allow for the camera to center when the chatbox is open, and to resize back to full height when it is closed, but it does require that the whole width of the viewport be covered by some type of chat overlay as seen in the image. Did my best not to make it look too janky. 
![image](https://github.com/user-attachments/assets/331d563d-fd03-41dc-8a46-493b1d0b7369)

I could also look into widening the chatbox interface, but it would add a bunch of contingencies i'd have to account for and likely a lot of bugs before it'd be working smoothly. Not sure if I want to do that.

**Comment by tremmelm123** [comment]
I'm alright with having to cover the whole width of the viewport. 

Are you familiar with the resizable chat plugin? Is there a way to allow for manual adjustment of the viewport from the user? I could then just try to match it with that chat.

**Comment by Lapask** [comment]
@tremmelm123 Okay I think i got the widened chat working natively on this plugin, so you shouldn't need that other plugin unless you want it.

The plugin will resize the viewport to center the player when the chat is open, and expand the viewport when the chat is closed. 
All dialogues will also be centered on the chat. Just putting some finishing touches on it (e.g. expanding the chat buttons on the bottom to fit the whole width. )

I'm hoping to get the update request on the plugin submitted sometime tomorrow, but it could take another couple of days to get accepted by the runelite team. 

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/eebeb1dc-3cb6-4af2-b878-038a512d4f74">

**Comment by tremmelm123** [comment]
This looks really good!

**Comment by Lapask** [comment]
Added in [aa53977252a8fc73ca041e7c0439e0316d6b969d](https://github.com/Lapask/fixed-resizable-hybrid/commit/aa53977252a8fc73ca041e7c0439e0316d6b969d).

**Comment by Lapask** [comment]
Added in [aa53977252a8fc73ca041e7c0439e0316d6b969d](https://github.com/Lapask/fixed-resizable-hybrid/commit/aa53977252a8fc73ca041e7c0439e0316d6b969d).
